### ISSUE TITLE
请教关于debug Vue程序

### ISSUE THREAD

**Issue by tyler5s** [jiangqizheng/vue-MiniQQ#1]
非常👍的项目！请教一个关于如何debug Vue程序的问题。

在使用过程中发现console抛了个错（删除一条对话，然后再进入任意余下的对话），npm run dev用的还是压缩过的app.js文件，完全无法定位到具体报错的程序逻辑，请问这种情况下需要怎么做呢？谢谢先～
![image](https://cloud.githubusercontent.com/assets/1539079/24389738/f5cf7096-13be-11e7-87e3-167075a6cff2.png)

**Comment by jiangqizheng** [comment]
- 首先，谢谢你的赞赏。

- 关于怎么在压缩状态下的报错怎么定位，说实话，我也正在寻找解决方案。（据说给每个组件添加name属性会有帮助）。

- 另外，已经修正相关的bug了，原因出在，点击打开对话框时，请求的数据是已经被删掉的数据，所以报错，刚刚已经更新了代码库，你可以查看我修改的地方，可以重新clone一份与之前的代码进行对比。

- 最后，感谢你的及时反馈，如果项目能帮到你就是再好不过了。
